services:
    task4-back-end:
        build:
            context: ./back-end
            dockerfile: Dockerfile

        image: task4-back-end
        ports:
            - "5252:5252"

    task4-front-end:
        build:
            context: ./front-end
            dockerfile: Dockerfile

        depends_on:
            - task4-back-end

        image: task4-front-end
        ports:
            - "9000:9000"

networks:
    default:
        driver: bridge
