services:
    task5-back-end:
        build:
            context: ./back-end
            dockerfile: Dockerfile

        image: task5-back-end
        expose:
            - "5252"

    task5-front-end:
        build:
            context: ./front-end
            dockerfile: Dockerfile

        depends_on:
            - task5-back-end

        image: task5-front-end
        expose:
            - "9000"

    proxy_server:
        build:
            context: ./proxy
            dockerfile: Dockerfile

        depends_on:
            - task5-back-end
            - task5-front-end

        image: proxy_server
        ports:
            - "80:80"

networks:
    default:
        driver: bridge
